version: '2'
services:
  proxy:
    image: traefik
    command: --web --docker
    labels:
      - "traefik.frontend.rule=Host:traefik.docker.localhost"
      - "traefik.enable=true"
      - "traefik.port=8080"
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml:ro
    container_name: traefik
    networks:
      - web
  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.docker.network=dev-gateway"
    restart: always
    networks:
      - web
    container_name: whoami
  maria:
    image: mariadb
    restart: always
    volumes:
      - mariadata:/var/lib/mysql
    labels:
      - "traefik.enable=false"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: dev
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    labels:
      - "traefik.frontend.rule=Host:adminer.docker.localhost"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=dev-gateway"
    networks:
      - backend
      - web
  wp:
    image: wordpress
    labels:
      - "traefik.frontend.rule=Host:wp.docker.localhost"
      - "traefik.enable=true"
      - "traefik.docker.network=dev-gateway"
    networks:
      - backend
      - web
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: maria
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: dev
      WORDPRESS_DB_NAME: wp
      WORDPRESS_TABLE_PREFIX: wp


networks:
  web:
    external:
      name: dev-gateway
  backend:
    external:
      name: dev-backend

volumes:
  mariadata: